#!/usr/bin/env bash
# Install nginx on your web-01

#updating and installing nginx
echo -e "\nUpdating..\n"
sudo apt-get -y update
sudo apt-get -y install nginx
#starting nginx service
echo -e "\nStarting nginx service\n"
sudo service nginx start
#allow nginx on firewall
sudo ufw allow "Nginx HTTP"
#give user ownership to webfiles for editing
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
echo -e "\nSuccessfully completed.\n"
