#!/usr/bin/env bash
Configure your Nginx server so that /redirect_me is redirecting to another page
WHERE="/etc/nginx/sites-available/default"
ADD="\\\tlocation \/redirect_me {\n\t\treturn 301 https://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

apt-get -y update
apt-get install -y nginx
echo "codingschool School" | sudo tee /usr/share/nginx/html/index.html
service nginx start
sed -i "30i $ADD" $WHERE
service nginx restart

