#!/usr/bin/env bash
# Configure new ubuntu machine by installing
# Nginx which should listen to port 80
# Serve a page returning Hello World string

#updating and installing nginx
echo -e "\nUpdating packages\n"
sudo apt-get -y update
sudo apt-get -y install nginx

#starting nginx service
echo -e "\nStarting nginx service\n"
sudo service nginx start

#allow nginx on firewall
sudo ufw allow "Nginx HTTP"

#give user ownership to webfiles for editing
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html

#setup /redirect_me to youtube
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

#restarting Nginx server
sudo service nginx restart
echo -e "\nSuccessfully completed.\n"

