#!/usr/bin/env bash
# installing load balancer with roundrobin
sudo apt-get update
sudo apt-get install -y software-properties-common
yes enter | sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install -y haproxy=1.8.\*
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.copy
sudo echo -e "\nfrontend http_front\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\nbackend http_back\n\tbalance roundrobin\n\tserver 12704-web-01 18.207.236.1:80 check\n\tserver 12704-web-02 35.153.18.115:80 check" >> /etc/haproxy/haproxy.cfg
sudo service rsyslog restart
sudo service haproxy restart
