#!/usr/bin/env bash
# Script that pings IP address passed as a string argument 5 times
IP="${1}"
# filename variable
fn=$(basename "${BASH_SOURCE[@]}")

if ! [ "$IP" ]; then
	echo "Usage: ${fn} {IP_ADDRESS}"
else
	ping -c 5 "${IP}"
fi