#!/usr/bin/env bash
# make nginx to listen to port 80
cd /etc/nginx/sites-enabled/ || exit;
rm default
# create symbolic link to default file in sites-available
ln -s /etc/nginx/sites-available/default default;
services nginx restart
