#!/usr/bin/env bash
# Bash script that display a list of currently running processes
# Shows all processes for all users, including non-TTY
# Displays in user oriented format and shows hierarchy

ps -a -x -u -f