#!/usr/bin/env bash
# Bash (init) script 101-manage_my_process that manages manage_my_process

case "$1" in
    start)
        # Start manage_my_process
        sudo ./manage_my_process start
        ;;
    stop)
        # Stop manage_my_process
        sudo ./manage_my_process stop
        ;;
    restart)
        # Restart manage_my_process
        sudo ./manage_my_process restart
        ;;
    *)
        # Display usage information
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
