#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20 and: displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration, displays 17 and then bad luck from Italy for the 17th loop iteration

hr=0
min=1
while [ $hr -lt 13 ]
do
    echo "Hour: $hr"
    while [ $min -lt 60 ]
    do
        echo $min
        min=$((min+1))
    done
    ((hr++))
    min=1
done