#!/usr/bin/env bash
# a Bash script that displays: The content of the current directory
# In a list format, Where only the part of the name after the first dash is displayed (refer to the example)


for file in *
do
    # Check if the file is not hidden and if it contains a dash
    if [[ ! "$file" == .* && "$file" == *-* ]]; then
        # Extract the part of the name after the first dash
        filename="${file#*-}"
        echo "$filename"
    fi
done