#!/usr/bin/env bash
# A bash script that displays all acive IPv4 addresses on the machine.
#ip address | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -d " " -f 2 -s
ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-