#!/usr/bin/env bash
# Make your fix short and sweet
sed -i 's/#user www-data/nginx/g' /etc/user nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
